export const FAKE_DATA = [
  {
    label: 'Blue',
    description: 'Claiborne',
    image: 'http://dummyimage.com/166x102.png/5fa2dd/ffffff',
    value: 'cwarry0@yandex.ru',
  },
  {
    label: 'Maroon',
    description: 'Courtenay',
    image: 'http://dummyimage.com/243x118.png/ff4444/ffffff',
    value: 'cwhacket1@earthlink.net',
  },
  {
    label: 'Khaki',
    description: 'Quintilla',
    image: 'http://dummyimage.com/136x217.png/5fa2dd/ffffff',
    value: 'qbeiderbeck2@nasa.gov',
  },
  {
    label: 'Yellow',
    description: 'Ricki',
    image: 'http://dummyimage.com/214x240.png/ff4444/ffffff',
    value: 'rrobelet3@bizjournals.com',
  },
  {
    label: 'Blue',
    description: 'Rania',
    image: 'http://dummyimage.com/247x199.png/dddddd/000000',
    value: 'rgullivent4@tamu.edu',
  },
  {
    label: 'Yellow',
    description: 'Shea',
    image: 'http://dummyimage.com/213x138.png/cc0000/ffffff',
    value: 'sswadden5@oracle.com',
  },
  {
    label: 'Purple',
    description: 'Ignacius',
    image: 'http://dummyimage.com/174x225.png/ff4444/ffffff',
    value: 'idanielut6@bing.com',
  },
  {
    label: 'Yellow',
    description: 'Danita',
    image: 'http://dummyimage.com/172x140.png/cc0000/ffffff',
    value: 'dlunam7@canalblog.com',
  },
  {
    label: 'Purple',
    description: 'Barnabe',
    image: 'http://dummyimage.com/125x111.png/5fa2dd/ffffff',
    value: 'bgodsil8@sohu.com',
  },
  {
    label: 'Aquamarine',
    description: 'Adan',
    image: 'http://dummyimage.com/172x106.png/ff4444/ffffff',
    value: 'aclaesens9@upenn.edu',
  },
  {
    label: 'Aquamarine',
    description: 'Timmie',
    image: 'http://dummyimage.com/227x143.png/cc0000/ffffff',
    value: 'tmeiklea@imdb.com',
  },
  {
    label: 'Goldenrod',
    description: 'Amaleta',
    image: 'http://dummyimage.com/189x111.png/5fa2dd/ffffff',
    value: 'agathererb@ustream.tv',
  },
  {
    label: 'Indigo',
    description: 'Larine',
    image: 'http://dummyimage.com/142x209.png/dddddd/000000',
    value: 'lharriec@so-net.ne.jp',
  },
  {
    label: 'Aquamarine',
    description: 'Oates',
    image: 'http://dummyimage.com/227x175.png/cc0000/ffffff',
    value: 'opruced@google.com.au',
  },
  {
    label: 'Mauv',
    description: 'Everard',
    image: 'http://dummyimage.com/198x201.png/ff4444/ffffff',
    value: 'eogdene@tiny.cc',
  },
  {
    label: 'Khaki',
    description: 'Les',
    image: 'http://dummyimage.com/215x178.png/5fa2dd/ffffff',
    value: 'leustanchf@canalblog.com',
  },
  {
    label: 'Teal',
    description: 'Toinette',
    image: 'http://dummyimage.com/141x140.png/dddddd/000000',
    value: 'ttabartg@squarespace.com',
  },
  {
    label: 'Aquamarine',
    description: 'Kata',
    image: 'http://dummyimage.com/168x184.png/5fa2dd/ffffff',
    value: 'kgoucherh@domainmarket.com',
  },
  {
    label: 'Crimson',
    description: 'Uri',
    image: 'http://dummyimage.com/102x231.png/ff4444/ffffff',
    value: 'uebbettsi@imageshack.us',
  },
  {
    label: 'Orange',
    description: 'Lorne',
    image: 'http://dummyimage.com/250x143.png/cc0000/ffffff',
    value: 'lwinterburnj@yellowbook.com',
  },
  {
    label: 'Turquoise',
    description: 'Sallyann',
    image: 'http://dummyimage.com/189x217.png/ff4444/ffffff',
    value: 'smorgank@paypal.com',
  },
  {
    label: 'Puce',
    description: 'Maddie',
    image: 'http://dummyimage.com/157x101.png/5fa2dd/ffffff',
    value: 'mmcphaill@tamu.edu',
  },
  {
    label: 'Aquamarine',
    description: 'Marietta',
    image: 'http://dummyimage.com/156x140.png/5fa2dd/ffffff',
    value: 'mlawiem@cocolog-nifty.com',
  },
  {
    label: 'Purple',
    description: 'Freemon',
    image: 'http://dummyimage.com/236x180.png/ff4444/ffffff',
    value: 'frotlaufn@wikia.com',
  },
  {
    label: 'Maroon',
    description: 'Jaymee',
    image: 'http://dummyimage.com/236x218.png/ff4444/ffffff',
    value: 'jdingo@google.com.br',
  },
  {
    label: 'Blue',
    description: 'Mollee',
    image: 'http://dummyimage.com/137x209.png/ff4444/ffffff',
    value: 'mmacadamp@woothemes.com',
  },
  {
    label: 'Green',
    description: 'Bordie',
    image: 'http://dummyimage.com/146x194.png/dddddd/000000',
    value: 'bnealandq@sun.com',
  },
  {
    label: 'Maroon',
    description: 'Michel',
    image: 'http://dummyimage.com/128x199.png/cc0000/ffffff',
    value: 'mmeffanr@i2i.jp',
  },
  {
    label: 'Crimson',
    description: 'Kylen',
    image: 'http://dummyimage.com/183x117.png/5fa2dd/ffffff',
    value: 'kcotess@boston.com',
  },
  {
    label: 'Teal',
    description: 'Korry',
    image: 'http://dummyimage.com/132x103.png/dddddd/000000',
    value: 'kguarniert@si.edu',
  },
  {
    label: 'Violet',
    description: 'Kalil',
    image: 'http://dummyimage.com/227x132.png/5fa2dd/ffffff',
    value: 'kdorbonu@rakuten.co.jp',
  },
  {
    label: 'Yellow',
    description: 'Lethia',
    image: 'http://dummyimage.com/239x182.png/dddddd/000000',
    value: 'lmallatrattv@unblog.fr',
  },
  {
    label: 'Pink',
    description: 'Lurleen',
    image: 'http://dummyimage.com/105x116.png/ff4444/ffffff',
    value: 'lmoralasw@sina.com.cn',
  },
  {
    label: 'Turquoise',
    description: 'Lindy',
    image: 'http://dummyimage.com/132x249.png/ff4444/ffffff',
    value: 'lgirkx@howstuffworks.com',
  },
  {
    label: 'Purple',
    description: 'Giovanna',
    image: 'http://dummyimage.com/116x204.png/cc0000/ffffff',
    value: 'gtosdeviny@phoca.cz',
  },
  {
    label: 'Purple',
    description: 'Zonda',
    image: 'http://dummyimage.com/138x132.png/cc0000/ffffff',
    value: 'zhaltz@howstuffworks.com',
  },
  {
    label: 'Fuscia',
    description: 'Donelle',
    image: 'http://dummyimage.com/108x219.png/dddddd/000000',
    value: 'dcrease10@tumblr.com',
  },
  {
    label: 'Pink',
    description: 'Gerrard',
    image: 'http://dummyimage.com/219x232.png/dddddd/000000',
    value: 'gfarress11@java.com',
  },
  {
    label: 'Purple',
    description: 'Minne',
    image: 'http://dummyimage.com/150x243.png/5fa2dd/ffffff',
    value: 'mshapter12@amazon.co.uk',
  },
  {
    label: 'Turquoise',
    description: 'Stanly',
    image: 'http://dummyimage.com/144x129.png/dddddd/000000',
    value: 'scockman13@mtv.com',
  },
  {
    label: 'Yellow',
    description: 'Vinson',
    image: 'http://dummyimage.com/167x216.png/dddddd/000000',
    value: 'vtallquist14@nsw.gov.au',
  },
  {
    label: 'Turquoise',
    description: 'Flore',
    image: 'http://dummyimage.com/181x184.png/cc0000/ffffff',
    value: 'fkeeble15@github.com',
  },
  {
    label: 'Puce',
    description: 'Robby',
    image: 'http://dummyimage.com/204x128.png/cc0000/ffffff',
    value: 'rwhittlesea16@phpbb.com',
  },
  {
    label: 'Goldenrod',
    description: 'Danya',
    image: 'http://dummyimage.com/135x127.png/5fa2dd/ffffff',
    value: 'dkalisz17@yale.edu',
  },
  {
    label: 'Indigo',
    description: 'Trip',
    image: 'http://dummyimage.com/136x171.png/5fa2dd/ffffff',
    value: 'tschwand18@wikia.com',
  },
  {
    label: 'Puce',
    description: 'Jackelyn',
    image: 'http://dummyimage.com/114x147.png/5fa2dd/ffffff',
    value: 'jvarvara19@zimbio.com',
  },
  {
    label: 'Purple',
    description: 'Carver',
    image: 'http://dummyimage.com/217x224.png/cc0000/ffffff',
    value: 'cvankin1a@netlog.com',
  },
  {
    label: 'Khaki',
    description: 'Merna',
    image: 'http://dummyimage.com/208x100.png/dddddd/000000',
    value: 'mkender1b@symantec.com',
  },
  {
    label: 'Turquoise',
    description: 'Emerson',
    image: 'http://dummyimage.com/191x214.png/5fa2dd/ffffff',
    value: 'eblaske1c@cafepress.com',
  },
  {
    label: 'Pink',
    description: 'Mick',
    image: 'http://dummyimage.com/159x147.png/5fa2dd/ffffff',
    value: 'mdoget1d@163.com',
  },
  {
    label: 'Khaki',
    description: 'Algernon',
    image: 'http://dummyimage.com/246x201.png/cc0000/ffffff',
    value: 'ahunnable1e@earthlink.net',
  },
  {
    label: 'Crimson',
    description: 'Rudolfo',
    image: 'http://dummyimage.com/181x240.png/5fa2dd/ffffff',
    value: 'rtapin1f@bigcartel.com',
  },
  {
    label: 'Blue',
    description: 'Eugine',
    image: 'http://dummyimage.com/185x224.png/ff4444/ffffff',
    value: 'etonn1g@gnu.org',
  },
  {
    label: 'Green',
    description: 'Fee',
    image: 'http://dummyimage.com/238x225.png/dddddd/000000',
    value: 'fmabb1h@bloomberg.com',
  },
  {
    label: 'Goldenrod',
    description: 'Zarah',
    image: 'http://dummyimage.com/119x201.png/cc0000/ffffff',
    value: 'zmacane1i@nationalgeographic.com',
  },
  {
    label: 'Puce',
    description: 'Laurens',
    image: 'http://dummyimage.com/221x180.png/dddddd/000000',
    value: 'lsiney1j@narod.ru',
  },
  {
    label: 'Yellow',
    description: 'Salvador',
    image: 'http://dummyimage.com/208x231.png/5fa2dd/ffffff',
    value: 'sdyment1k@chicagotribune.com',
  },
  {
    label: 'Turquoise',
    description: 'Nial',
    image: 'http://dummyimage.com/206x191.png/ff4444/ffffff',
    value: 'nuccelli1l@naver.com',
  },
  {
    label: 'Yellow',
    description: 'Sigfrid',
    image: 'http://dummyimage.com/142x182.png/5fa2dd/ffffff',
    value: 'swapple1m@smh.com.au',
  },
  {
    label: 'Puce',
    description: 'Mill',
    image: 'http://dummyimage.com/195x182.png/ff4444/ffffff',
    value: 'mlatan1n@sfgate.com',
  },
  {
    label: 'Teal',
    description: 'Germaine',
    image: 'http://dummyimage.com/101x204.png/dddddd/000000',
    value: 'gscholes1o@google.com.au',
  },
  {
    label: 'Violet',
    description: 'Lodovico',
    image: 'http://dummyimage.com/151x159.png/ff4444/ffffff',
    value: 'lpossa1p@simplemachines.org',
  },
  {
    label: 'Violet',
    description: 'Gareth',
    image: 'http://dummyimage.com/214x190.png/5fa2dd/ffffff',
    value: 'gcanto1q@google.com.hk',
  },
  {
    label: 'Fuscia',
    description: 'Rosemarie',
    image: 'http://dummyimage.com/112x219.png/cc0000/ffffff',
    value: 'rmanzell1r@squidoo.com',
  },
  {
    label: 'Crimson',
    description: 'Jeana',
    image: 'http://dummyimage.com/244x223.png/dddddd/000000',
    value: 'jphilpotts1s@wordpress.org',
  },
  {
    label: 'Orange',
    description: 'Holli',
    image: 'http://dummyimage.com/103x227.png/cc0000/ffffff',
    value: 'hvaughten1t@nhs.uk',
  },
  {
    label: 'Crimson',
    description: 'Garvin',
    image: 'http://dummyimage.com/231x132.png/5fa2dd/ffffff',
    value: 'gsainsberry1u@woothemes.com',
  },
  {
    label: 'Goldenrod',
    description: 'Isak',
    image: 'http://dummyimage.com/183x243.png/5fa2dd/ffffff',
    value: 'igoodred1v@google.de',
  },
  {
    label: 'Aquamarine',
    description: 'Stefania',
    image: 'http://dummyimage.com/224x103.png/dddddd/000000',
    value: 'sjerzak1w@msn.com',
  },
  {
    label: 'Khaki',
    description: 'Evangeline',
    image: 'http://dummyimage.com/188x178.png/5fa2dd/ffffff',
    value: 'edegnen1x@cornell.edu',
  },
  {
    label: 'Pink',
    description: 'Ettore',
    image: 'http://dummyimage.com/151x179.png/cc0000/ffffff',
    value: 'ewinchcombe1y@weibo.com',
  },
  {
    label: 'Mauv',
    description: 'Hughie',
    image: 'http://dummyimage.com/126x110.png/cc0000/ffffff',
    value: 'hgino1z@narod.ru',
  },
  {
    label: 'Yellow',
    description: 'Vilma',
    image: 'http://dummyimage.com/171x180.png/dddddd/000000',
    value: 'vcracknell20@yahoo.co.jp',
  },
  {
    label: 'Blue',
    description: 'Paloma',
    image: 'http://dummyimage.com/210x248.png/5fa2dd/ffffff',
    value: 'phayward21@mozilla.com',
  },
  {
    label: 'Pink',
    description: 'Carmelina',
    image: 'http://dummyimage.com/182x134.png/ff4444/ffffff',
    value: 'cchadbourne22@businessinsider.com',
  },
  {
    label: 'Yellow',
    description: 'Torin',
    image: 'http://dummyimage.com/122x243.png/5fa2dd/ffffff',
    value: 'tmacdiarmond23@t.co',
  },
  {
    label: 'Purple',
    description: 'Bartram',
    image: 'http://dummyimage.com/131x152.png/ff4444/ffffff',
    value: 'baxelbee24@google.com.au',
  },
  {
    label: 'Goldenrod',
    description: 'Ogdon',
    image: 'http://dummyimage.com/224x194.png/dddddd/000000',
    value: 'otrosdall25@artisteer.com',
  },
  {
    label: 'Orange',
    description: 'Gianni',
    image: 'http://dummyimage.com/141x231.png/cc0000/ffffff',
    value: 'gjepson26@wp.com',
  },
  {
    label: 'Turquoise',
    description: 'Matt',
    image: 'http://dummyimage.com/149x107.png/cc0000/ffffff',
    value: 'mdodle27@lulu.com',
  },
  {
    label: 'Maroon',
    description: 'Selia',
    image: 'http://dummyimage.com/157x120.png/5fa2dd/ffffff',
    value: 'schimes28@blog.com',
  },
  {
    label: 'Khaki',
    description: 'Jeane',
    image: 'http://dummyimage.com/201x249.png/cc0000/ffffff',
    value: 'jprandin29@ted.com',
  },
  {
    label: 'Violet',
    description: 'Julian',
    image: 'http://dummyimage.com/228x202.png/ff4444/ffffff',
    value: 'jsoppit2a@behance.net',
  },
  {
    label: 'Teal',
    description: 'Hartley',
    image: 'http://dummyimage.com/236x111.png/ff4444/ffffff',
    value: 'hcorkel2b@example.com',
  },
  {
    label: 'Yellow',
    description: 'Louella',
    image: 'http://dummyimage.com/133x236.png/5fa2dd/ffffff',
    value: 'lepp2c@jimdo.com',
  },
  {
    label: 'Fuscia',
    description: 'Cherish',
    image: 'http://dummyimage.com/161x175.png/5fa2dd/ffffff',
    value: 'ckembery2d@cbslocal.com',
  },
  {
    label: 'Pink',
    description: 'Clarence',
    image: 'http://dummyimage.com/190x209.png/ff4444/ffffff',
    value: 'csmelley2e@joomla.org',
  },
  {
    label: 'Mauv',
    description: 'Mike',
    image: 'http://dummyimage.com/249x204.png/cc0000/ffffff',
    value: 'mcowburn2f@chicagotribune.com',
  },
  {
    label: 'Violet',
    description: 'Eldin',
    image: 'http://dummyimage.com/117x222.png/ff4444/ffffff',
    value: 'egamet2g@miitbeian.gov.cn',
  },
  {
    label: 'Goldenrod',
    description: 'Adamo',
    image: 'http://dummyimage.com/131x205.png/cc0000/ffffff',
    value: 'ablackboro2h@si.edu',
  },
  {
    label: 'Aquamarine',
    description: 'Alexandros',
    image: 'http://dummyimage.com/150x209.png/5fa2dd/ffffff',
    value: 'ajepperson2i@shareasale.com',
  },
  {
    label: 'Khaki',
    description: 'Eddy',
    image: 'http://dummyimage.com/201x173.png/cc0000/ffffff',
    value: 'eheenan2j@tripod.com',
  },
  {
    label: 'Aquamarine',
    description: 'Chandal',
    image: 'http://dummyimage.com/229x119.png/cc0000/ffffff',
    value: 'csherrin2k@ycombinator.com',
  },
  {
    label: 'Aquamarine',
    description: 'Filbert',
    image: 'http://dummyimage.com/178x140.png/dddddd/000000',
    value: 'fvalintine2l@ted.com',
  },
  {
    label: 'Fuscia',
    description: 'Roslyn',
    image: 'http://dummyimage.com/221x156.png/5fa2dd/ffffff',
    value: 'rbarfford2m@geocities.com',
  },
  {
    label: 'Violet',
    description: 'Marie-jeanne',
    image: 'http://dummyimage.com/116x122.png/ff4444/ffffff',
    value: 'mrosin2n@forbes.com',
  },
  {
    label: 'Purple',
    description: 'Stefania',
    image: 'http://dummyimage.com/226x239.png/ff4444/ffffff',
    value: 'sgeekin2o@blinklist.com',
  },
  {
    label: 'Indigo',
    description: 'Noel',
    image: 'http://dummyimage.com/208x100.png/5fa2dd/ffffff',
    value: 'nvancassel2p@nba.com',
  },
  {
    label: 'Green',
    description: 'Jamie',
    image: 'http://dummyimage.com/239x146.png/dddddd/000000',
    value: 'jemig2q@friendfeed.com',
  },
  {
    label: 'Violet',
    description: 'Tull',
    image: 'http://dummyimage.com/139x186.png/ff4444/ffffff',
    value: 'tmonnoyer2r@java.com',
  },
];
